name: pytest unit tests and coverage  
  
on:

  push:
    branches:
      - main

  pull_request:
  
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10", "3.11"]  
  
    steps:  
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          pip install .
          python -m pip install -U pytest coverage
      - name: Test with pytest  
        run: coverage run -m pytest -v -s
      - name: Generate Coverage Report  
        run: coverage report -m
